<template><div><h1 id="_1-查询结果反射结构体-mysql" tabindex="-1"><a class="header-anchor" href="#_1-查询结果反射结构体-mysql" aria-hidden="true">#</a> 1. 查询结果反射结构体(mysql)</h1>
<p>本文讲解的实例是从mysql查询过来的数据如何反射到结构体字段,具体实现方法如下代码;</p>
<p>代码目录：</p>
<p>1129</p>
<p>-common</p>
<p>--common.go //是封装的代码</p>
<p>-main.go //是测试代码</p>
<p>代码的封装：</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">package</span> common

<span class="token keyword">import</span> <span class="token punctuation">(</span>
    <span class="token string">"errors"</span>
    <span class="token string">"reflect"</span>
    <span class="token string">"strconv"</span>
    <span class="token string">"time"</span>
<span class="token punctuation">)</span>

<span class="token comment">//根据结构体中sql标签映射数据到结构体中并且转换类型</span>
<span class="token keyword">func</span> <span class="token function">DataToStructByTagSql</span><span class="token punctuation">(</span>data <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">,</span> obj <span class="token keyword">interface</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    objValue <span class="token operator">:=</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>obj<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Elem</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token keyword">for</span> i <span class="token operator">:=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> objValue<span class="token punctuation">.</span><span class="token function">NumField</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> i<span class="token operator">++</span> <span class="token punctuation">{</span>
        <span class="token comment">//获取sql对应的值</span>
        value <span class="token operator">:=</span> data<span class="token punctuation">[</span>objValue<span class="token punctuation">.</span><span class="token function">Type</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Field</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">.</span>Tag<span class="token punctuation">.</span><span class="token function">Get</span><span class="token punctuation">(</span><span class="token string">"sql"</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
        <span class="token comment">//获取对应字段的名称</span>
        name <span class="token operator">:=</span> objValue<span class="token punctuation">.</span><span class="token function">Type</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Field</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">.</span>Name
        <span class="token comment">//获取对应字段类型</span>
        structFieldType <span class="token operator">:=</span> objValue<span class="token punctuation">.</span><span class="token function">Field</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Type</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token comment">//获取变量类型，也可以直接写"string类型"</span>
        val <span class="token operator">:=</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span>
        <span class="token keyword">var</span> err <span class="token builtin">error</span>
        <span class="token keyword">if</span> structFieldType <span class="token operator">!=</span> val<span class="token punctuation">.</span><span class="token function">Type</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">//类型转换</span>
            val<span class="token punctuation">,</span> err <span class="token operator">=</span> <span class="token function">TypeConversion</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> structFieldType<span class="token punctuation">.</span><span class="token function">Name</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token comment">//类型转换</span>
            <span class="token keyword">if</span> err <span class="token operator">!=</span> <span class="token boolean">nil</span> <span class="token punctuation">{</span>

            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
        <span class="token comment">//设置类型值</span>
        objValue<span class="token punctuation">.</span><span class="token function">FieldByName</span><span class="token punctuation">(</span>name<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span>val<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token comment">//类型转换</span>
<span class="token keyword">func</span> <span class="token function">TypeConversion</span><span class="token punctuation">(</span>value <span class="token builtin">string</span><span class="token punctuation">,</span> ntype <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token punctuation">(</span>reflect<span class="token punctuation">.</span>Value<span class="token punctuation">,</span> <span class="token builtin">error</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"string"</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token boolean">nil</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"time.Time"</span> <span class="token punctuation">{</span>
        t<span class="token punctuation">,</span> err <span class="token operator">:=</span> time<span class="token punctuation">.</span><span class="token function">ParseInLocation</span><span class="token punctuation">(</span><span class="token string">"2006-01-02 15:04:05"</span><span class="token punctuation">,</span> value<span class="token punctuation">,</span> time<span class="token punctuation">.</span>Local<span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>t<span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"Time"</span> <span class="token punctuation">{</span>
        t<span class="token punctuation">,</span> err <span class="token operator">:=</span> time<span class="token punctuation">.</span><span class="token function">ParseInLocation</span><span class="token punctuation">(</span><span class="token string">"2006-01-02 15:04:05"</span><span class="token punctuation">,</span> value<span class="token punctuation">,</span> time<span class="token punctuation">.</span>Local<span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>t<span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"int"</span> <span class="token punctuation">{</span>
        i<span class="token punctuation">,</span> err <span class="token operator">:=</span> strconv<span class="token punctuation">.</span><span class="token function">Atoi</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"int8"</span> <span class="token punctuation">{</span>
        i<span class="token punctuation">,</span> err <span class="token operator">:=</span> strconv<span class="token punctuation">.</span><span class="token function">ParseInt</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span><span class="token function">int8</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"int32"</span> <span class="token punctuation">{</span>
        i<span class="token punctuation">,</span> err <span class="token operator">:=</span> strconv<span class="token punctuation">.</span><span class="token function">ParseInt</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span><span class="token function">int64</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"int64"</span> <span class="token punctuation">{</span>
        i<span class="token punctuation">,</span> err <span class="token operator">:=</span> strconv<span class="token punctuation">.</span><span class="token function">ParseInt</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"float32"</span> <span class="token punctuation">{</span>
        i<span class="token punctuation">,</span> err <span class="token operator">:=</span> strconv<span class="token punctuation">.</span><span class="token function">ParseFloat</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span><span class="token function">float32</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> ntype <span class="token operator">==</span> <span class="token string">"float64"</span> <span class="token punctuation">{</span>
        i<span class="token punctuation">,</span> err <span class="token operator">:=</span> strconv<span class="token punctuation">.</span><span class="token function">ParseFloat</span><span class="token punctuation">(</span>value<span class="token punctuation">,</span> <span class="token number">64</span><span class="token punctuation">)</span>
        <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">,</span> err
    <span class="token punctuation">}</span>

    <span class="token comment">//else if .......增加其他一些类型的转换</span>

    <span class="token keyword">return</span> reflect<span class="token punctuation">.</span><span class="token function">ValueOf</span><span class="token punctuation">(</span>value<span class="token punctuation">)</span><span class="token punctuation">,</span> errors<span class="token punctuation">.</span><span class="token function">New</span><span class="token punctuation">(</span><span class="token string">"未知的类型："</span> <span class="token operator">+</span> ntype<span class="token punctuation">)</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>代码的测试：</p>
<div class="language-go ext-go line-numbers-mode"><pre v-pre class="language-go"><code><span class="token keyword">package</span> main

<span class="token keyword">import</span> <span class="token punctuation">(</span>
    <span class="token string">"fmt"</span>

    <span class="token string">"github.com/student/1129/common"</span>
<span class="token punctuation">)</span>

<span class="token comment">//Product Product定义一个结构体</span>
<span class="token keyword">type</span> Product <span class="token keyword">struct</span> <span class="token punctuation">{</span>
    ID           <span class="token builtin">int64</span>  <span class="token string">`json:"id" sql:"id"`</span>
    ProductClass <span class="token builtin">string</span> <span class="token string">`json:"ProductClass" sql:"ProductClass"`</span>
    ProductName  <span class="token builtin">string</span> <span class="token string">`json:"ProductName" sql:"productName"`</span>
    ProductNum   <span class="token builtin">int64</span>  <span class="token string">`json:"ProductNum" sql:"productNum"`</span>
    ProductImage <span class="token builtin">string</span> <span class="token string">`json:"ProductImage" sql:"productImage"`</span>
    ProductURL   <span class="token builtin">string</span> <span class="token string">`json:"ProductUrl" sql:"productUrl" `</span>
<span class="token punctuation">}</span>

<span class="token keyword">func</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">//这块是模拟mysql获取单条的数据反射到结构体</span>
    data <span class="token operator">:=</span> <span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span><span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token string">"1"</span><span class="token punctuation">,</span> <span class="token string">"ProductClass"</span><span class="token punctuation">:</span> <span class="token string">"blog"</span><span class="token punctuation">,</span> <span class="token string">"productName"</span><span class="token punctuation">:</span> <span class="token string">"5lmh.com"</span><span class="token punctuation">,</span> <span class="token string">"productNum"</span><span class="token punctuation">:</span> <span class="token string">"40"</span><span class="token punctuation">,</span> <span class="token string">"productImage"</span><span class="token punctuation">:</span> <span class="token string">"http://www.5lmh.com/"</span><span class="token punctuation">,</span> <span class="token string">"productUrl"</span><span class="token punctuation">:</span> <span class="token string">"http://www.5lmh.com/"</span><span class="token punctuation">}</span>
    productResult <span class="token operator">:=</span> <span class="token operator">&amp;</span>Product<span class="token punctuation">{</span><span class="token punctuation">}</span>
    common<span class="token punctuation">.</span><span class="token function">DataToStructByTagSql</span><span class="token punctuation">(</span>data<span class="token punctuation">,</span> productResult<span class="token punctuation">)</span>
    fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span><span class="token operator">*</span>productResult<span class="token punctuation">)</span>
    <span class="token comment">//这块是模拟mysql获取所有的数据反射到结构体</span>
    Alldata <span class="token operator">:=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token keyword">map</span><span class="token punctuation">[</span><span class="token builtin">string</span><span class="token punctuation">]</span><span class="token builtin">string</span><span class="token punctuation">{</span>
        <span class="token punctuation">{</span><span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token string">"1"</span><span class="token punctuation">,</span> <span class="token string">"ProductClass"</span><span class="token punctuation">:</span> <span class="token string">"blog"</span><span class="token punctuation">,</span> <span class="token string">"productName"</span><span class="token punctuation">:</span> <span class="token string">"5lmh.com"</span><span class="token punctuation">,</span> <span class="token string">"productNum"</span><span class="token punctuation">:</span> <span class="token string">"40"</span><span class="token punctuation">,</span> <span class="token string">"productImage"</span><span class="token punctuation">:</span> <span class="token string">"http://www.5lmh.com/"</span><span class="token punctuation">,</span> <span class="token string">"productUrl"</span><span class="token punctuation">:</span> <span class="token string">"http://www.5lmh.com/"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
        <span class="token punctuation">{</span><span class="token string">"id"</span><span class="token punctuation">:</span> <span class="token string">"2"</span><span class="token punctuation">,</span> <span class="token string">"ProductClass"</span><span class="token punctuation">:</span> <span class="token string">"blog"</span><span class="token punctuation">,</span> <span class="token string">"productName"</span><span class="token punctuation">:</span> <span class="token string">"5lmh.com"</span><span class="token punctuation">,</span> <span class="token string">"productNum"</span><span class="token punctuation">:</span> <span class="token string">"40"</span><span class="token punctuation">,</span> <span class="token string">"productImage"</span><span class="token punctuation">:</span> <span class="token string">"http://www.5lmh.com/"</span><span class="token punctuation">,</span> <span class="token string">"productUrl"</span><span class="token punctuation">:</span> <span class="token string">"http://www.5lmh.com/"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">var</span> productArray <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token operator">*</span>Product
    <span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> v <span class="token operator">:=</span> <span class="token keyword">range</span> Alldata <span class="token punctuation">{</span>
        Allproduct <span class="token operator">:=</span> <span class="token operator">&amp;</span>Product<span class="token punctuation">{</span><span class="token punctuation">}</span>
        common<span class="token punctuation">.</span><span class="token function">DataToStructByTagSql</span><span class="token punctuation">(</span>v<span class="token punctuation">,</span> Allproduct<span class="token punctuation">)</span>
        productArray <span class="token operator">=</span> <span class="token function">append</span><span class="token punctuation">(</span>productArray<span class="token punctuation">,</span> Allproduct<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">for</span> <span class="token boolean">_</span><span class="token punctuation">,</span> vv <span class="token operator">:=</span> <span class="token keyword">range</span> productArray <span class="token punctuation">{</span>
        fmt<span class="token punctuation">.</span><span class="token function">Println</span><span class="token punctuation">(</span>vv<span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="end-链接" tabindex="-1"><a class="header-anchor" href="#end-链接" aria-hidden="true">#</a> END 链接</h2>
<ul><li><div><a href = '83.md' style='float:left'>⬆️上一节🔗</a><a href = '85.md' style='float: right'>⬇️下一节🔗</a></div></li></ul>
<ul>
<li>
<p><RouterLink to="/Gomd_super/">Ⓜ️回到首页🏠</RouterLink></p>
</li>
<li>
<p><a href="https://nsddd.top/archives/contributors" target="_blank" rel="noopener noreferrer"><strong>🫵参与贡献💞❤️‍🔥💖</strong><ExternalLinkIcon/></a>)</p>
</li>
<li>
<p>✴️版权声明 © :本书所有内容遵循<a href="http://zh.wikipedia.org/wiki/Wikipedia:CC-by-sa-3.0%E5%8D%8F%E8%AE%AE%E6%96%87%E6%9C%AC" target="_blank" rel="noopener noreferrer">CC-BY-SA 3.0协议（署名-相同方式共享）©<ExternalLinkIcon/></a></p>
</li>
</ul>
</div></template>


